#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner
[ -e /tmp/.failsafe ] && cat /etc/banner.failsafe

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

export SERIAL_NUM="SPKA19$(head -c 280 /dev/mtd2 | tail -c 8)"

# migration path... if the serial number is invalid, use the mac
if [ "$SERIAL_NUM" = "SPKA19SERIALNO" ]; then
    export SERIAL_NUM="TwistSpeaker-$(od -tx1 -j 7 -N 3 -An /dev/mtd2 | tr -d ' ')"
fi